# Base image
FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Copy client files
COPY ./client /usr/src/app

# Install dependencies
RUN npm install && npm run build

# Install `serve` globally
RUN npm install -g serve

# Expose the application port
EXPOSE 3000

# Command to serve the built application
CMD ["serve", "-s", "build"]
