version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    ports:
      - "5002:5002"
    volumes:
      - ./server:/usr/src/app
    stdin_open: true
    tty: true

  client:
    build:
      context: .
      dockerfile: client/Dockerfile.client
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
