# Use an official Node.js image as the base
FROM node:16

# Install MongoDB using the official MongoDB apt repository
RUN apt-get update && apt-get install -y gnupg wget \
    && wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - \
    && echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list \
    && apt-get update && apt-get install -y mongodb-org \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /usr/src/app

# Copy the server files
COPY ./server /usr/src/app

# Install Node.js dependencies
RUN npm install

# Expose necessary ports
EXPOSE 5002

# Copy the setup script
COPY ./server/setup.sh /usr/src/app/setup.sh

# Make the script executable
RUN chmod +x /usr/src/app/setup.sh

# Entry point to run the setup script
ENTRYPOINT ["sh", "/usr/src/app/setup.sh"]
