services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://mongodb:27017/livechat
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  mongo-data:
